import os
import re
import sqlite3
import math
import json
import urllib.request
import urllib.error
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

from flask import Flask, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "emails.db"

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "dev-secret-change-in-production")
USE_EXTERNAL_AI = os.environ.get("USE_EXTERNAL_AI", "false").lower() == "true"

ML_CLASSES = ("Legitimate", "Spam", "Fraud")
SEED_DATASET = [
    ("Legitimate", "meeting agenda attached for tomorrow project sync and notes"),
    ("Legitimate", "invoice paid successfully and receipt generated by trusted vendor"),
    ("Legitimate", "family dinner plan this weekend let us confirm the timing"),
    ("Legitimate", "your subscription renewal has been processed thank you"),
    ("Spam", "limited offer click now free coupons win cashback today"),
    ("Spam", "buy followers instantly huge discount promotion click here"),
    ("Spam", "congratulations you won lottery prize claim reward now"),
    ("Spam", "earn money fast work from home guaranteed profits"),
    ("Fraud", "urgent verify your account now or it will be suspended"),
    ("Fraud", "security alert reset your password immediately click here"),
    ("Fraud", "wire transfer required immediately to secure this transaction"),
    ("Fraud", "send gift card codes to complete payment confirmation"),
]


def tokenize(text: str):
    return re.findall(r"[a-z]{2,}", text.lower())


def train_naive_bayes(dataset):
    class_counts = Counter()
    word_counts = {label: Counter() for label in ML_CLASSES}
    total_words = Counter()
    vocabulary = set()

    for label, text in dataset:
        class_counts[label] += 1
        tokens = tokenize(text)
        word_counts[label].update(tokens)
        total_words[label] += len(tokens)
        vocabulary.update(tokens)

    return {
        "class_counts": class_counts,
        "word_counts": word_counts,
        "total_words": total_words,
        "vocabulary": vocabulary,
        "total_docs": len(dataset),
    }


NB_MODEL = train_naive_bayes(SEED_DATASET)
DEMO_EMAIL_CASES = [
    {
        "title": "Fraud Example: Fake Security Alert",
        "sender": "security@account-protect-center.net",
        "subject": "Urgent: Verify your account now",
        "body": "Your account is suspended. Click here to reset your password immediately!!! http://secure-now-check.com",
    },
    {
        "title": "Spam Example: Prize Bait",
        "sender": "promo@mega-prize-cash.com",
        "subject": "Congratulations! Claim your lottery reward",
        "body": "You won free money today. Click here now to claim your prize and cashback.",
    },
    {
        "title": "Legitimate Example: Team Update",
        "sender": "manager@company.com",
        "subject": "Project meeting notes for Monday",
        "body": "Please review the meeting agenda and share updates before tomorrow's sync.",
    },
]


def ml_predict_category(sender: str, subject: str, body: str):
    text = f"{sender} {subject} {body}"
    tokens = tokenize(text)
    if not tokens:
        return "Legitimate", 50, "No meaningful words for ML analysis"

    model = NB_MODEL
    vocab_size = max(len(model["vocabulary"]), 1)
    log_scores = {}
    token_impact = defaultdict(float)

    for label in ML_CLASSES:
        prior = (model["class_counts"][label] + 1) / (model["total_docs"] + len(ML_CLASSES))
        log_prob = math.log(prior)
        denominator = model["total_words"][label] + vocab_size
        for token in tokens:
            token_count = model["word_counts"][label][token]
            token_prob = (token_count + 1) / denominator
            token_log_prob = math.log(token_prob)
            log_prob += token_log_prob
            token_impact[(label, token)] += token_log_prob
        log_scores[label] = log_prob

    top_label = max(log_scores, key=log_scores.get)
    max_log = max(log_scores.values())
    probs = {label: math.exp(log_scores[label] - max_log) for label in ML_CLASSES}
    total_prob = sum(probs.values()) or 1
    normalized = {label: probs[label] / total_prob for label in ML_CLASSES}
    confidence = int(round(normalized[top_label] * 100))

    ranked_tokens = sorted(
        [(token, token_impact[(top_label, token)]) for token in set(tokens)],
        key=lambda item: item[1],
        reverse=True,
    )[:4]
    important_tokens = ", ".join(token for token, _score in ranked_tokens) or "none"
    ml_reason = f"ML confidence {confidence}% ({top_label}); key tokens: {important_tokens}"
    return top_label, confidence, ml_reason


def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(_error):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    db = get_db()
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS emails (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            sender TEXT NOT NULL,
            subject TEXT NOT NULL,
            body TEXT NOT NULL,
            category TEXT NOT NULL,
            risk_score INTEGER NOT NULL,
            reasons TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
        """
    )
    db.commit()


def classify_email(sender: str, subject: str, body: str):
    text = f"{sender} {subject} {body}".lower()
    score = 0
    reasons = []

    fraud_keywords = [
        ("urgent", 12, "Urgency language detected"),
        ("verify your account", 25, "Account verification bait detected"),
        ("bank", 10, "Banking context detected"),
        ("suspended", 18, "Threat-style language detected"),
        ("reset your password", 20, "Password reset lure detected"),
        ("wire transfer", 30, "Wire-transfer fraud pattern detected"),
        ("gift card", 22, "Gift card payment request detected"),
        ("crypto", 12, "Crypto payment language detected"),
        ("click here", 12, "Suspicious click prompt detected"),
        ("lottery", 18, "Prize/lottery pattern detected"),
        ("free money", 20, "Too-good-to-be-true offer detected"),
        ("social security", 25, "Sensitive data targeting detected"),
    ]

    for keyword, points, reason in fraud_keywords:
        if keyword in text:
            score += points
            reasons.append(reason)

    domain_match = re.search(r"@([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})", sender)
    if domain_match:
        domain = domain_match.group(1).lower()
        trusted_domains = {"gmail.com", "outlook.com", "yahoo.com", "apple.com", "microsoft.com", "amazon.com"}
        if domain not in trusted_domains and any(
            x in text for x in ["bank", "microsoft", "apple id", "amazon support", "security team"]
        ):
            score += 20
            reasons.append("Possible sender impersonation detected")
    else:
        score += 15
        reasons.append("Malformed sender email format")

    suspicious_link_count = len(re.findall(r"http[s]?://", body.lower()))
    if suspicious_link_count >= 2:
        score += 15
        reasons.append("Multiple links detected in email body")

    if len(re.findall(r"[!]{2,}", subject + body)) > 0:
        score += 10
        reasons.append("Aggressive punctuation style detected")

    rule_score = min(score, 100)
    rule_category = "Legitimate"
    if rule_score >= 65:
        rule_category = "Fraud"
    elif rule_score >= 40:
        rule_category = "Spam"

    ml_category, ml_confidence, ml_reason = ml_predict_category(sender, subject, body)
    reasons.append(ml_reason)

    category_rank = {"Legitimate": 0, "Spam": 1, "Fraud": 2}
    blended_rule_weight = 0.6
    blended_ml_weight = 0.4
    blended_value = (category_rank[rule_category] * blended_rule_weight) + (
        category_rank[ml_category] * blended_ml_weight
    )

    if blended_value >= 1.5:
        category = "Fraud"
    elif blended_value >= 0.7:
        category = "Spam"
    else:
        category = "Legitimate"

    if not reasons:
        reasons.append("No suspicious patterns found")

    final_risk_score = int(round((rule_score * 0.7) + (ml_confidence * 0.3)))
    return category, final_risk_score, " | ".join(reasons), ml_confidence, "local"


def _call_gemini(sender: str, subject: str, body: str):
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if not gemini_key:
        return None

    prompt = (
        "Classify this email into one label only: Legitimate, Spam, or Fraud. "
        "Then provide risk_score (0-100), ml_confidence (0-100), and short reason. "
        "Return ONLY JSON with keys: category, risk_score, ml_confidence, reasons.\n\n"
        f"Sender: {sender}\nSubject: {subject}\nBody: {body}"
    )
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"responseMimeType": "application/json"},
    }
    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"gemini-1.5-flash:generateContent?key={gemini_key}"
    )
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=20) as response:
        raw = json.loads(response.read().decode("utf-8"))
    text = raw["candidates"][0]["content"]["parts"][0]["text"]
    parsed = json.loads(text)
    parsed["source"] = "gemini"
    return parsed


def _call_openai(sender: str, subject: str, body: str):
    openai_key = os.environ.get("OPENAI_API_KEY")
    if not openai_key:
        return None

    payload = {
        "model": os.environ.get("OPENAI_MODEL", "gpt-4o-mini"),
        "temperature": 0.2,
        "response_format": {"type": "json_object"},
        "messages": [
            {
                "role": "system",
                "content": (
                    "You classify emails as Legitimate, Spam, or Fraud. "
                    "Return JSON only with keys: category, risk_score, ml_confidence, reasons."
                ),
            },
            {
                "role": "user",
                "content": f"Sender: {sender}\nSubject: {subject}\nBody: {body}",
            },
        ],
    }
    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {openai_key}"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=20) as response:
        raw = json.loads(response.read().decode("utf-8"))
    parsed = json.loads(raw["choices"][0]["message"]["content"])
    parsed["source"] = "openai"
    return parsed


def external_ai_classify(sender: str, subject: str, body: str):
    if not USE_EXTERNAL_AI:
        return None
    try:
        provider = os.environ.get("AI_PROVIDER", "gemini").lower()
        if provider == "openai":
            return _call_openai(sender, subject, body)
        return _call_gemini(sender, subject, body)
    except (urllib.error.URLError, urllib.error.HTTPError, KeyError, ValueError, json.JSONDecodeError):
        return None


def current_user():
    uid = session.get("user_id")
    if not uid:
        return None
    user = get_db().execute("SELECT id, username FROM users WHERE id = ?", (uid,)).fetchone()
    return user


def build_proxy_email(username: str):
    safe_name = re.sub(r"[^a-zA-Z0-9]", "", username.lower()) or "demo"
    return f"{safe_name}.proxy@spammail-demo.test"


@app.route("/")
def index():
    user = current_user()
    if user:
        return redirect(url_for("dashboard"))
    return render_template("index.html")


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        if len(username) < 3 or len(password) < 6:
            flash("Username must be 3+ chars and password 6+ chars.")
            return redirect(url_for("register"))

        db = get_db()
        try:
            db.execute(
                "INSERT INTO users (username, password_hash, created_at) VALUES (?, ?, ?)",
                (username, generate_password_hash(password, method="pbkdf2:sha256"), datetime.utcnow().isoformat()),
            )
            db.commit()
            flash("Account created. Please login.")
            return redirect(url_for("login"))
        except sqlite3.IntegrityError:
            flash("Username already exists.")
            return redirect(url_for("register"))
    return render_template("register.html")


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        user = get_db().execute(
            "SELECT id, username, password_hash FROM users WHERE username = ?",
            (username,),
        ).fetchone()

        if not user or not check_password_hash(user["password_hash"], password):
            flash("Invalid username or password.")
            return redirect(url_for("login"))

        session["user_id"] = user["id"]
        flash("Logged in successfully.")
        return redirect(url_for("dashboard"))
    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out.")
    return redirect(url_for("index"))


@app.route("/dashboard", methods=["GET", "POST"])
def dashboard():
    user = current_user()
    if not user:
        return redirect(url_for("login"))

    result = None
    if request.method == "POST":
        sender = request.form.get("sender", "").strip()
        subject = request.form.get("subject", "").strip()
        body = request.form.get("body", "").strip()
        if not sender or not subject or not body:
            flash("Please fill all email fields.")
            return redirect(url_for("dashboard"))

        local_category, local_risk_score, local_reasons, local_ml_confidence, source = classify_email(sender, subject, body)
        external = external_ai_classify(sender, subject, body)
        if external:
            category = external.get("category", local_category)
            risk_score = int(external.get("risk_score", local_risk_score))
            ml_confidence = int(external.get("ml_confidence", local_ml_confidence))
            reasons = f"{external.get('reasons', local_reasons)} | Provider: {external.get('source', 'external')}"
            source = external.get("source", source)
        else:
            category = local_category
            risk_score = local_risk_score
            reasons = local_reasons
            ml_confidence = local_ml_confidence
        get_db().execute(
            """
            INSERT INTO emails (user_id, sender, subject, body, category, risk_score, reasons, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (user["id"], sender, subject, body, category, risk_score, reasons, datetime.utcnow().isoformat()),
        )
        get_db().commit()
        result = {
            "category": category,
            "risk_score": risk_score,
            "reasons": reasons,
            "ml_confidence": ml_confidence,
            "source": source,
        }

    history = get_db().execute(
        """
        SELECT sender, subject, category, risk_score, reasons, created_at
        FROM emails WHERE user_id = ? ORDER BY id DESC LIMIT 10
        """,
        (user["id"],),
    ).fetchall()

    proxy_email = build_proxy_email(user["username"])
    return render_template(
        "dashboard.html",
        user=user,
        result=result,
        history=history,
        proxy_email=proxy_email,
        demo_email_cases=DEMO_EMAIL_CASES,
    )


with app.app_context():
    init_db()


if __name__ == "__main__":
    debug_mode = os.environ.get("FLASK_DEBUG", "false").lower() == "true"
    app.run(debug=debug_mode, host="0.0.0.0", port=int(os.environ.get("PORT", "5000")))
